# see: https://www.youtube.com/watch?v=mGspM-cFEgE
# https://devices.esphome.io/devices/Generic-PIR

esphome:
  name: pir-sensor
  friendly_name: pir_sensor

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xx/xx+xxx="

ota:
  - platform: esphome
    password: "xxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pir-Sensor Fallback Hotspot"
    password: "xxxxxxx"

captive_portal:

binary_sensor:
  - platform: gpio
    pin: 12
    name: "PIR Sensor"
    device_class: motion
